import Link from "next/link";
import { getPrimitives, getTensions, getFindings } from "@/lib/data/synthesis";
import { getAllSpecimens } from "@/lib/data/specimens";

export const metadata = {
  title: "Analytical Framework — Field Guide to AI Organizations",
  description: "The theoretical backbone: 5 primitives predict organizational AI structure, generating 5 tensions and 10 consolidated findings",
};

const PRIMITIVE_COLORS: Record<string, string> = {
  P1: "bg-forest-50 text-forest border-forest-200",
  P2: "bg-amber-50 text-amber-700 border-amber-200",
  P3: "bg-violet-50 text-violet-700 border-violet-200",
  P4: "bg-sky-50 text-sky-700 border-sky-200",
  P5: "bg-rose-50 text-rose-700 border-rose-200",
};

const PRIMITIVE_ACCENT: Record<string, string> = {
  P1: "border-l-forest",
  P2: "border-l-amber",
  P3: "border-l-violet-500",
  P4: "border-l-sky-500",
  P5: "border-l-rose-400",
};

export default async function FrameworkPage() {
  const [primitiveData, tensionData, findingData, specimens] = await Promise.all([
    getPrimitives(),
    getTensions(),
    getFindings(),
    getAllSpecimens(),
  ]);

  return (
    <div className="space-y-12">
      {/* Header */}
      <header>
        <p className="font-mono text-xs uppercase tracking-[0.2em] text-sage-500">
          Analytical Framework
        </p>
        <h1 className="mt-2 font-serif text-3xl font-semibold text-forest">
          How Do Organizations Structure for AI?
        </h1>
        <p className="mt-3 max-w-3xl text-charcoal-500">
          The observed variation in AI organizational structure (157 specimens across 9 models &times; 3 orientations)
          is generated by a small number of <strong>primitive variables</strong>. These are the independent variables
          in our theory. Everything else &mdash; the tensions organizations face, the mechanisms they deploy, the
          patterns we observe &mdash; derives from interactions among these primitives.
        </p>
      </header>

      {/* The 5 Primitives */}
      <section>
        <h2 className="mb-6 font-serif text-2xl text-forest">
          The 5 Primitives
        </h2>
        <p className="mb-6 text-sm text-charcoal-500">
          What predicts structural choice? Five independent variables, rooted in organizational economics.
        </p>
        <div className="grid gap-4 lg:grid-cols-5">
          {primitiveData.primitives.map((p) => (
            <div
              key={p.id}
              className={`rounded-lg border-l-4 bg-white p-5 shadow-sm ${PRIMITIVE_ACCENT[p.shortId] || "border-l-sage"}`}
            >
              <div className="flex items-center gap-2">
                <span className={`rounded px-2 py-0.5 font-mono text-xs font-bold ${PRIMITIVE_COLORS[p.shortId] || ""}`}>
                  {p.shortId}
                </span>
              </div>
              <h3 className="mt-2 font-serif text-base font-medium text-forest">
                {p.name}
              </h3>
              <p className="mt-2 text-xs leading-relaxed text-charcoal-500">
                {p.definition.split(".").slice(0, 2).join(".") + "."}
              </p>
              <div className="mt-3">
                <p className="text-[10px] font-medium uppercase tracking-wide text-charcoal-400">
                  Sub-dimensions
                </p>
                <ul className="mt-1 space-y-0.5">
                  {p.subDimensions.map((sd) => (
                    <li key={sd.id} className="text-[10px] text-charcoal-500">
                      {sd.name}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="mt-3">
                <p className="text-[10px] font-medium uppercase tracking-wide text-charcoal-400">
                  Generates tensions
                </p>
                <div className="mt-1 flex flex-wrap gap-1">
                  {p.generatesTensions.map((tid) => (
                    <span key={tid} className="rounded bg-sage-50 px-1.5 py-0.5 font-mono text-[10px] text-sage-700">
                      T{tid}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Primitives → Tensions Flow */}
      <section>
        <h2 className="mb-4 font-serif text-2xl text-forest">
          How Primitives Generate Tensions
        </h2>
        <p className="mb-6 text-sm text-charcoal-500">
          The tensions in our framework are tradeoffs that organizations face when structuring for ambidexterity.
          They are <strong>derived from</strong> the primitives, not independent of them.
        </p>
        <div className="space-y-4">
          {tensionData.tensions.map((t) => (
            <div
              key={t.id}
              className={`rounded-lg border bg-cream-50 p-5 ${
                t.masterTension ? "border-amber-400 ring-1 ring-amber-200" : "border-sage-200"
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-sm text-charcoal-400">T{t.id}</span>
                  <h3 className="font-serif text-lg font-medium text-forest">
                    {t.name}
                  </h3>
                  {t.masterTension && (
                    <span className="rounded-full bg-amber-100 px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-widest text-amber-700">
                      Master Tension
                    </span>
                  )}
                </div>
                <Link
                  href="/tensions"
                  className="shrink-0 text-xs text-forest hover:underline"
                >
                  View on map &rarr;
                </Link>
              </div>
              <p className="mt-1 text-sm text-charcoal-600">{t.tradeoff}</p>

              {/* Derived from */}
              {t.derivedFrom && (
                <div className="mt-3 flex items-center gap-2">
                  <span className="text-[10px] font-medium uppercase tracking-wide text-charcoal-400">
                    Derived from:
                  </span>
                  {t.derivedFrom.primitives.map((pid) => (
                    <span
                      key={pid}
                      className={`rounded px-1.5 py-0.5 font-mono text-[10px] font-bold ${PRIMITIVE_COLORS[pid] || "bg-sage-50 text-sage-700"}`}
                    >
                      {pid}
                    </span>
                  ))}
                  <span className="text-[10px] text-charcoal-400">
                    {t.derivedFrom.explanation.split(".")[0] + "."}
                  </span>
                </div>
              )}

              {/* Caveat for T4 */}
              {t.caveat && (
                <div className="mt-2 rounded border border-amber-200 bg-amber-50 px-3 py-2">
                  <p className="text-[10px] italic text-amber-700">
                    {t.caveat.split(".").slice(0, 2).join(".") + "."}
                  </p>
                </div>
              )}

              {/* Specimen count */}
              <p className="mt-2 text-[10px] text-charcoal-400">
                {t.specimens.length} specimens positioned
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* The 10 Findings */}
      <section>
        <h2 className="mb-4 font-serif text-2xl text-forest">
          10 Consolidated Findings
        </h2>
        <p className="mb-6 text-sm text-charcoal-500">
          78 field insights consolidated into 10 core findings that do genuine theoretical work.
          Each is grounded in the primitives, generates testable predictions, and is supported by multiple specimens.
        </p>
        <div className="space-y-4">
          {findingData.findings.map((f) => {
            const evidenceSpecimens = f.evidence.slice(0, 5).map((e) => {
              const spec = specimens.find((s) => s.id === e.specimenId);
              return { id: e.specimenId, name: spec?.name ?? e.specimenId };
            });

            return (
              <Link
                key={f.id}
                href="/findings"
                className="group block rounded-lg border border-sage-200 bg-cream-50 p-5 transition-shadow hover:shadow-md"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-sm text-charcoal-400">
                        F{f.number}
                      </span>
                      <h3 className="font-serif text-base font-medium text-forest group-hover:text-forest-600">
                        {f.title}
                      </h3>
                    </div>
                  </div>
                  <span
                    className={`shrink-0 rounded px-2 py-0.5 text-[10px] font-medium ${
                      f.maturity === "confirmed"
                        ? "bg-forest-50 text-forest"
                        : f.maturity === "emerging"
                        ? "bg-amber-50 text-amber-700"
                        : "bg-rose-50 text-rose-600"
                    }`}
                  >
                    {f.maturity}
                  </span>
                </div>

                {/* Primitives engaged */}
                <div className="mt-2 flex items-center gap-1.5">
                  {f.primitivesEngaged.map((pid) => (
                    <span
                      key={pid}
                      className={`rounded px-1.5 py-0.5 font-mono text-[10px] font-bold ${PRIMITIVE_COLORS[pid] || "bg-sage-50 text-sage-700"}`}
                    >
                      {pid}
                    </span>
                  ))}
                </div>

                {/* Claim excerpt */}
                <p className="mt-2 line-clamp-2 text-sm text-charcoal-600">
                  {f.claim}
                </p>

                {/* Evidence specimens */}
                <div className="mt-3 flex flex-wrap gap-1">
                  {evidenceSpecimens.map((s) => (
                    <span
                      key={s.id}
                      className="rounded bg-sage-50 px-1.5 py-0.5 text-[10px] text-sage-600"
                    >
                      {s.name}
                    </span>
                  ))}
                  {f.evidence.length > 5 && (
                    <span className="text-[10px] text-charcoal-400">
                      +{f.evidence.length - 5} more
                    </span>
                  )}
                </div>
              </Link>
            );
          })}
        </div>
        <div className="mt-6 text-center">
          <Link
            href="/findings"
            className="font-mono text-sm text-forest hover:underline"
          >
            View all findings with full evidence &rarr;
          </Link>
        </div>
      </section>

      {/* Papers */}
      <section className="rounded-lg border border-sage-200 bg-white p-6">
        <h2 className="mb-4 font-serif text-xl text-forest">
          Papers Latent in This Material
        </h2>
        <div className="grid gap-4 md:grid-cols-3">
          <div className="rounded border border-sage-100 bg-cream-50 p-4">
            <p className="font-mono text-[10px] uppercase tracking-wide text-sage-500">
              Paper 1
            </p>
            <p className="mt-1 font-serif text-sm font-medium text-forest">
              Structure Follows Architecture
            </p>
            <p className="mt-1 text-xs text-charcoal-500">
              The mirroring thesis + governance constraints + industry convergence.
              Findings 1, 3, 4, 5, 6, 7.
            </p>
          </div>
          <div className="rounded border border-sage-100 bg-cream-50 p-4">
            <p className="font-mono text-[10px] uppercase tracking-wide text-sage-500">
              Paper 2
            </p>
            <p className="mt-1 font-serif text-sm font-medium text-forest">
              The Moral Hazard of AI Transition
            </p>
            <p className="mt-1 text-xs text-charcoal-500">
              Measurement &rarr; overcorrection &rarr; reversal chain + tacit knowledge destruction.
              Findings 2, 10.
            </p>
          </div>
          <div className="rounded border border-sage-100 bg-cream-50 p-4">
            <p className="font-mono text-[10px] uppercase tracking-wide text-sage-500">
              Paper 3
            </p>
            <p className="mt-1 font-serif text-sm font-medium text-forest">
              Purpose and Structure as Complements
            </p>
            <p className="mt-1 text-xs text-charcoal-500">
              Purpose rhetoric and organizational structure are complementary practices.
              Finding 8.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
